trigger:
  - main
  - master

pr:
  - main
  - master

pool:
  vmImage: ubuntu-latest

container: azdevcliextacr.azurecr.io/azure-dev:latest

steps:
  - task: AzureCLI@2
    displayName: Provision and Deploy
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd provision --no-prompt
        azd deploy --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: $(AZURE_SUBSCRIPTION_ID)
      AZURE_ENV_NAME: $(AZURE_ENV_NAME)
      AZURE_LOCATION: $(AZURE_LOCATION)
