on:
  workflow_dispatch:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: azdevcliextacr.azurecr.io/azure-dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Dev Deploy
        run: az dev deploy -e ${{ secrets.AZURE_ENV_NAME }}
